---
version: 3

images:
  base_image:
    name: 'quay.io/centos/centos:stream8'

dependencies:
  python_interpreter:
    package_system: python39
    python_path: /usr/bin/python3.9

  ansible_core:
    package_pip: ansible-core==2.12.10

  ansible_runner:
    package_pip: ansible-runner

  galaxy: requirements.yml

  python: requirements.txt

  system: bindep.txt

additional_build_steps:
  append_final:
    - RUN echo "#!/bin/sh" > /opt/.ansible-vault.env
    - RUN echo "echo \$ANSIBLE_VAULT_PASSWORD" >> /opt/.ansible-vault.env
    - RUN chmod +x /opt/.ansible-vault.env
    - RUN dnf -y install dnf-plugins-core
    - RUN dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
    - RUN dnf -y install docker-ce-cli

options:
  user: root
