---
name: jrgoldfinemiddleton.digitalocean.dummy

on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - "!roles/dummy/**.md"
      - "roles/dummy/**"
      - "Makefile"
      - ".github/workflows/dummy.yml"

jobs:
  molecule_default:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
          - docker

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Molecule scenario ${{ matrix.scenario }}
        run: make test
        env:
          ANSIBLE_MOLECULE_ROLE: dummy
          ANSIBLE_MOLECULE_SCENARIO: ${{ matrix.scenario }}
          # TODO: consider removing the custom group
          ANSIBLE_MOLECULE_GROUP: dummy_group
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
